#!/usr/bin/env sh

SOURCE_DIR="wp-content/plugins/woo-passentry-plugin"
DEST_DIR="woo-passentry-plugin"

echo "Updating files from plugin directory to root"

if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: Source directory $SOURCE_DIR does not exist"
    exit 1
fi


find "$DEST_DIR" -maxdepth 1 -type f \( -name "*.php" -o -name "*.txt" \) -exec rm -f {} +


cp -R "$SOURCE_DIR"/* "$DEST_DIR"/ || {
    echo "Error: Failed to copy files from $SOURCE_DIR to $DEST_DIR"
    exit 1
}


if [ $? -eq 0 ]; then
    echo "Successfully copied files and subdirectories"
else
    echo "Failed to copy files"
    exit 1
fi

git add .

exit 0